---
title: "RandomForest for diet"
output: html_notebook
---

```{r}
setwd("~/Documents/MultiTisssueDiet")
WeightData <- read.csv("~/Documents/MultiTisssueDiet/d_20162021_BXDMultiTissueDiet_Williams_mRNA_DATAwithPhenos.csv",row.names= 1, header=F,sep=",", na.strings="")
NewWeightData <- WeightData[, which(colMeans(!is.na(WeightData)) > 0.5)]
NewWeightData <- NewWeightData[ -c(1:3), ]
WData <- as.data.frame (t(NewWeightData))

Samples<-WData[ c(1,2,4,6) ]
Samples[Samples=="CD"]<-0
Samples[Samples=="HF"]<-1
Samples[Samples=="Quadriceps"]<-0
Samples[Samples=="scWAT"]<-1
Samples[Samples=="Intestine"]<-2
Samples[Samples=="Heart"]<-3
Samples[Samples=="Liver"]<-4
Samples[Samples=="BAT"]<-5


NewWData<-cbind(Samples,WData)
NewWData <- as.data.frame(t(NewWData))
#Quadriceps_green <- read.csv("~/Documents/MultiTisssueDiet/scWATgreen")
#NewWData <- NewWData[row.names(NewWData) %in% Quadriceps_green$`cyt.nodeData.nodeName`,]
NewWData<-cbind(Samples,t(NewWData))
NewWData<-NewWData[-c(1:2),-c(1,2,5:15)]

QWData <- NewWData[NewWData$Tissue == "0",]
sWData <- NewWData[NewWData$Tissue == "1",]
IWData <- NewWData[NewWData$Tissue == "2",]
HWData <- NewWData[NewWData$Tissue == "3",]
LWData <- NewWData[NewWData$Tissue == "4",]

```

```{r}
## train and test sets 
data_ <- QWData
data_<- as.data.frame(data_)
metadata <- as.matrix(as.factor(data_$Diet))
data_ <- lapply(data_,as.numeric)
 data_ <- as.data.frame(data_)
```

```{r}
# download libraries
library(dplyr)      # data splitting 
library(randomForest) # basic implementation
```

```{r}
# train data 80 % and test data 20 %
library(tidyverse)
library(caret)
random_sample <- createDataPartition(data_ $Diet,
                                p = 0.8, list = FALSE)
train <- data_[random_sample, ]
Train<-train[-c(1,2)]
test <- data_[-random_sample,]
Test <-test[-c(1,2)]
```



```{r}

### Random Forest
library(randomForest)
#resRF<-randomForest(train$Diet~.,train[,-1] )
resRF <- randomForest(x =Train[, colnames(Train) != "respvar"],
                   y = as.factor(train$Diet), ntree = 100)
plot(resRF)
resRF

```
```{r}
## variable importance
var_imp <- importance(resRF, type = 2)
 Genes = row.names(var_imp)
 importantVariabels= as.data.frame(cbind(Genes,var_imp))
 importantVariabels = importantVariabels[importantVariabels$MeanDecreaseGini > 0,]
```

```{r}
## parameters estimation 
vecmtry=c(3,5,10,20,30,40,50,100)
vecntree=c(10,20,30,40,50,100,200)
matres=matrix(NA,length(vecmtry),length(vecntree))
for (i in 1:length(vecmtry))
  
{
  for (j in 1:length(vecntree))
  {
    resRFloc<-randomForest(x =Train[, colnames(Train) != "respvar"],
                   y = as.factor(train$Diet) ,mtry=vecmtry[i],ntree=vecntree[j])
    matres[i,j]=resRFloc$err.rate[vecntree[j],1]
  }
}	
rownames(matres)=vecmtry	
colnames(matres)=vecntree
print(matres)



```

```{r}
# adjusted RandomForest

resRF<-randomForest(x =Train[, colnames(Train) != "respvar"],
                   y = as.factor(train$Diet), ntree=100,mtry=100,localImp = TRUE)
summary(resRF)
plot(resRF)
resRF


```






```{r}
#Variabels importance
library(randomForestExplainer)
importance_frame <- measure_importance(resRF)
plot_multi_way_importance(importance_frame,  size_measure = "p_value",main = "Importance of variables"
                          , )
varImpPlot(resRF)
var_imp <- importance(resRF, type = 2)
 Genes = row.names(var_imp)
 importantVariabels= as.data.frame(cbind(Genes,var_imp))
 importantVariabels = importantVariabels[importantVariabels$MeanDecreaseGini > 0,]
```

```{r}
# validation of the model
TestDataLiver = LWData[-c(1,2)]
TestDataLiver <- lapply(TestDataLiver,as.numeric)
TestDataLiver <- as.data.frame(TestDataLiver)


#pred_test <- predict(resRF, TestDataLiver,type = "prob")
pred_test <- predict(resRF, Test,type = "prob")

library(ROCR)                          

library(pROC)
pred_test_roc <- roc(as.factor(test$Diet),pred_test[,2])
#pred_test_roc <- roc(as.factor(LWData$Diet),pred_test[,2])

plot(pred_test_roc)
pred_test_roc
library(ggplot2)
ggroc(pred_test_roc, lwd=1.2, col="blue")+
geom_abline(intercept = 1, slope = 1, color = "red", linetype = "dashed", lwd=1.2)

```

```{r}
rf <- list()
varIm= list()
Genes <- list()
importantGenes <- list()
for (iter in 1:1000)
  {
  rf[[iter]] <- randomForest(x =Train[, colnames(Train) != "respvar"],
                   y = as.factor(train$Diet), ntree=50,mtry=40,localImp = TRUE)
  varIm[[iter]]=importance(rf[[iter]])
    Genes[[iter]] = row.names(varIm[[iter]])
 importantGenes[[iter]]= as.data.frame(cbind(Genes[[iter]],varIm[[iter]]))
 importantGenes[[iter]] = importantGenes[[iter]][importantGenes[[iter]]$MeanDecreaseGini > 0.5,]
 #varImpPlot(rf[[iter]])
}
 

count <- table(unlist(lapply(importantGenes, unique)))
count<-as.data.frame(count)
```

```{r}

pred_test <- list()
pred_test_roc <- list ()
auc <- list()
for (iter in 1:1000)
  {
  rf[[iter]] <- randomForest(x =Train[, colnames(Train) != "respvar"],
                   y = as.factor(train$Diet), ntree=50,mtry=40,localImp = TRUE)
  
  pred_test[[iter]] <- predict(rf[[iter]], TestDataLiver,type = "prob")
  


library(ROCR)                          

library(pROC)
pred_test_roc[[iter]]<- roc(as.factor(QWData$Diet),pred_test[[iter]][,2])
  auc[[iter]]<- auc(pred_test_roc[[iter]])
library(ggplot2)
ggroc(pred_test_roc[[iter]], lwd=1.2, col="blue")+
geom_abline(intercept = 1, slope = 1, color = "red", linetype = "dashed", lwd=1.2)


}
AUC4 <-  unlist(auc)

boxplot(AUC1,AUC2,AUC3,AUC4,AUC5,AUC6,AUC7,xlab="methods",ylab="AUC", main = "Boxplots of AUC of the different predictions via Random Forest", col= "lightblue", names = c("QDiet","LDiet","Q->L","L->Q","LNew","QWeight","LWeight"), legend=T)
```
 
 