---
title: "R Notebook"
output: html_notebook
---
title: "RF liver for bodyweight prediction"
output: html_notebook
---
```{r}
setwd("~/Documents/MultiTisssueDiet")
WeightData <- read.csv("~/Documents/MultiTisssueDiet/d_20162021_BXDMultiTissueDiet_Williams_mRNA_DATAwithPhenos.csv",row.names= 1, header=F,sep=",", na.strings="")
NewWeightData <- WeightData[, which(colMeans(!is.na(WeightData)) > 0.5)]
NewWeightData <- NewWeightData[ -c(1:3), ]
WData <- as.data.frame (t(NewWeightData))

WData$Bodyweight <- cut(as.numeric(WData$Bodyweight),
              breaks=c(26, 38,50, 62),
              labels=c('1', '2','3'))

Samples<-WData[ c(1,2,4,6) ]
Samples[Samples=="CD"]<-0
Samples[Samples=="HF"]<-1
Samples[Samples=="Quadriceps"]<-0
Samples[Samples=="scWAT"]<-1
Samples[Samples=="Intestine"]<-2
Samples[Samples=="Heart"]<-3
Samples[Samples=="Liver"]<-4
Samples[Samples=="BAT"]<-5

#rownames(WData)<- WData$V2
DeG <- read.csv("~/Documents/MultiTisssueDiet/scWATgreen")
WData <- as.data.frame(t(WData))
#WData <- WData[row.names(WData) %in% DeG$X,]
NewWData<-cbind(Samples, t(WData))
LWData <- NewWData[NewWData$Tissue == "4",]
LWData <- as.data.frame(LWData[-c(1,2),-c(1,3,4)])

QWData <- NewWData[NewWData$Tissue == "0",]
QWData <- as.data.frame(QWData[-c(1,2),-c(1,3:10)])

sWData <- NewWData[NewWData$Tissue == "1",]
sWData <- as.data.frame(sWData[-c(1,2),-c(1,3:11)])

#TestDiet <- Header$Diet
#TestDiet <- TestDiet[-c(1,2)]

```

```{r}
## train and test sets 
library(tidyverse)
library(caret)
data_ <- sWData
data_<- as.data.frame(data_)
#metadata <- as.matrix(as.factor(data_$Bodyweight))
data_ <- lapply(data_,as.numeric)
 data_ <- as.data.frame(data_)
random_sample <- createDataPartition(data_ $Bodyweight,
                              p = 0.8, list = FALSE)
train <- data_[random_sample, ]
Train<-train[-c(1,2)]
test <- data_[-random_sample,]
Test <-test[-c(1,2)]
```

```{r}
# download libraries
library(dplyr)      # data splitting 
library(randomForest) # basic implementation
```




```{r}

### Random Forest
library(randomForest)
#resRF<-randomForest(train$Diet~.,train[,-1] )
resRF <- randomForest(x =Train[, colnames(Train) != "respvar"],
                   y = as.factor(train$Bodyweight), ntree = 100)
plot(resRF)
resRF

```
```{r}
## variable import
var_imp <- importance(resRF, type = 2)
 Genes = row.names(var_imp)
 importantVariabels= as.data.frame(cbind(Genes,var_imp))
 importantVariabels = importantVariabels[importantVariabels$MeanDecreaseGini > 0,]
```

```{r}
## parameters estimation 
vecmtry=c(3,5,10,20,30,40,50,100)
vecntree=c(10,20,30,40,50,100,200)
matres=matrix(NA,length(vecmtry),length(vecntree))
for (i in 1:length(vecmtry))
  
{
  for (j in 1:length(vecntree))
  {
    resRFloc<-randomForest(x =Train[, colnames(Train) != "respvar"],
                   y = as.factor(train$Bodyweight) ,mtry=vecmtry[i],ntree=vecntree[j])
    matres[i,j]=resRFloc$err.rate[vecntree[j],1]
  }
}	
rownames(matres)=vecmtry	
colnames(matres)=vecntree
print(matres)



```

```{r}
# adjusted RandomForest


resRF<-randomForest(x =Train[, colnames(Train) != "respvar"],
                   y = as.factor(train$Bodyweight), ntree=100,mtry=50,localImp = TRUE)
#summary(resRF)
#plot(resRF)
#resRF

#Variabels importance
library(randomForestExplainer)
importance_frame <- measure_importance(resRF)
selected_genes<-importance_frame 

#plot_multi_way_importance(importance_frame,  size_measure = "p_value",main = "Importance of variables", )
#varImpPlot(resRF)

# validation of the model

pred_test <- predict(resRF, Test,type = "prob")

library(ROCR)                          
library(pROC)
pred_test_roc <- multiclass.roc(test$Bodyweight,pred_test)

 
plot(pred_test_roc$auc)


```
```{r}
rf <- list()
varIm= list()
Genes <- list()
importantGenes <- list()
for (iter in 1:1000)
  {
  rf[[iter]] <- randomForest(x =Train[, colnames(Train) != "respvar"],
                   y = as.factor(train$Bodyweight), ntree=40,mtry=20,localImp = TRUE)
  varIm[[iter]]=importance(rf[[iter]])
    Genes[[iter]] = row.names(varIm[[iter]])
 importantGenes[[iter]]= as.data.frame(cbind(Genes[[iter]],varIm[[iter]]))
 importantGenes[[iter]] = importantGenes[[iter]][importantGenes[[iter]]$MeanDecreaseGini > 0.5,]
 
}
 
count <- table(unlist(lapply(importantGenes, unique)))
count<-as.data.frame(count)
```

```{r}
pred_test <- list()
pred_test_roc <- list ()
auc <- list()
for (iter in 1:1000)
  {
  rf[[iter]] <- randomForest(x =Train[, colnames(Train) != "respvar"],
                   y = as.factor(train$Bodyweight), ntree=50,mtry=40,localImp = TRUE)
  
  pred_test[[iter]] <- predict(rf[[iter]], Test,type = "prob")
  


library(ROCR)                          

library(pROC)
pred_test_roc[[iter]]<- roc(as.factor(test$Bodyweight),pred_test[[iter]][,2])
  auc[[iter]]<- auc(pred_test_roc[[iter]])
library(ggplot2)
ggroc(pred_test_roc[[iter]], lwd=1.2, col="blue")+
geom_abline(intercept = 1, slope = 1, color = "red", linetype = "dashed", lwd=1.2)


}
AUC7 <-  unlist(auc)
```

