# WAGCNA 


# Set up environment
```{r}
#clear workspace and set string as factors to false
#rm(list=ls())
options(stringsAsFactors = F)

```

# Install required packages
```{r}
if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
#uncomment if not yet installed!
#BiocManager::install(c("WGCNA","rstudioapi","dplyr"))

library(WGCNA)
library(rstudioapi)
library(dplyr)
```

```{r}
setwd("~/Documents/MultiTisssueDiet")
```

# read data and combine them to input file for WGCNA

```{r}
#Download Data
setwd("~/Documents/MultiTisssueDiet")
MultiTissueData=read.table("d_20162021_BXDMultiTissueDiet_Williams_mRNA_DATAwithPhenos.csv", row.names = 1,header=F, skip=2 ,sep=",", na.strings="")
Genes <- MultiTissueData[c(1)]
Genes <- Genes[-c(1:7),]

NewData <- MultiTissueData[, which(colMeans(!is.na(MultiTissueData)) > 0.5)]
NewData <- NewData[ -c(1,2,4,6,8), ]
WData <- as.data.frame (t(NewData))

Samples<-WData[ c(1:3) ]
Samples[Samples=="CD"]<-0
Samples[Samples=="HF"]<-1
Samples[Samples=="Quadriceps"]<-0
Samples[Samples=="scWAT"]<-1
Samples[Samples=="Intestine"]<-2
Samples[Samples=="Heart"]<-3
Samples[Samples=="Liver"]<-4
Samples[Samples=="BAT"]<-5
Samples$Bodyweight<- as.numeric(Samples$Bodyweight)

NewData<-cbind(Samples,WData)
NewData<-NewData[-c(4:6)]
QData <- NewData[NewData$Tissue == "0",]
sData <- NewData[NewData$Tissue == "1",]
IData <- NewData[NewData$Tissue == "2",]
HData <- NewData[NewData$Tissue == "3",]
LData <- NewData[NewData$Tissue == "4",]

```




```{r}
# replace QData by another tissue's data to analyse futher organs
data <- as.data.frame(QData[-c(1:2),-c(1:3)])
data <- lapply(data,as.numeric)
data <- as.data.frame(data)
gsg = goodSamplesGenes(data, verbose = 3);
gsg$allOK

```
```{r}
#log2 transformation

data.log <- log2(data+1)
data.log <- as.data.frame(as.matrix(data.log))
```



```{r}


# Form a data frame analogous to expression data that will hold the clinical traits.

traitData = QData[1:3]
traitData=traitData[-c(1:2),]
data.filtered.dcm = data.log
datTraits = traitData
datTraits <- mutate_all(datTraits, function(x) as.numeric(as.character(x)))
```

#merge together the filtered table with the information from the Giannakis dataset
```{r}
# Cluster samples
Data1 <- dist(data.filtered.dcm)

sampleTree = hclust(dist(data.filtered.dcm), method = "average")

# Convert traits to a color representation: white means low, red means high, grey means missing entry
traitColors = numbers2colors(datTraits, signed = FALSE);
sizeGrWindow(12,12)

# Plot the sample dendrogram and the colors underneath.
plotDendroAndColors(sampleTree, traitColors,
                    groupLabels = names(datTraits), cex.dendroLabels = 0.5, 
                    main = "Sample dendrogram and trait heatmap")
```

```{r}
save(data.filtered.dcm, datTraits, file = "WGCNA-input.RData")
```





#########################################
Network construction and module detection
#########################################

```{r}
#enableWGCNAThreads()
# Load the data 
lnames = load(file = "WGCNA-input.RData");
#The variable lnames contains the names of loaded variables.
lnames
```

```{r}
# Choose a set of soft-thresholding powers
powers = seq(1,15, by=2)

# Call the network topology analysis function
sft = pickSoftThreshold(data.filtered.dcm, powerVector = powers, verbose = 5)

#save(sft, file = "WGCNA-sft.RData")

# Plot the results:
sizeGrWindow(9, 5)
par(mfrow = c(1,2));
cex1 = 0.9;

# Scale-free topology fit index as a function of the soft-thresholding power
plot(sft$fitIndices[,1], -sign(sft$fitIndices[,3])*sft$fitIndices[,2], xlab="Soft Threshold (power)",ylab="Scale Free Topology Model Fit,signed R^2",type="n", main = paste("Scale independence"));

text(sft$fitIndices[,1], -sign(sft$fitIndices[,3])*sft$fitIndices[,2], labels=powers,cex=cex1,col="red");

# this line corresponds to using an R^2 cut-off of h
abline(h=0.80,col="red")

# Mean connectivity as a function of the soft-thresholding power
plot(sft$fitIndices[,1], sft$fitIndices[,5], xlab="Soft Threshold (power)",ylab="Mean Connectivity", type="n", main = paste("Mean connectivity"))

text(sft$fitIndices[,1], sft$fitIndices[,5], labels=powers, cex=cex1,col="red")
```

```{r}
# looking at both - soft threshold and mean connectivity 
# I decided to go with power 5 
net = blockwiseModules(data.filtered.dcm, power = 5,
                       TOMType = "unsigned", minModuleSize = 30,
                       reassignThreshold = 0, mergeCutHeight = 0.25,
                       numericLabels = TRUE, pamRespectsDendro = FALSE,
                       saveTOMs = TRUE,
                       saveTOMFileBase = "expTOM", 
                       verbose = 3)

#save(net, file = "WGCNA-net.RData")

```


```{r}
# open a graphics window
sizeGrWindow(15, 9)
# Convert labels to colors for plotting
mergedColors = labels2colors(net$colors)
# Plot the dendrogram and the module colors underneath
plotDendroAndColors(net$dendrograms[[1]], mergedColors[net$blockGenes[[1]]],
                    "Module colors",
                    dendroLabels = FALSE, hang = 0.03,
                    addGuide = TRUE, guideHang = 0.05)
```

```{r}
moduleLabels = net$colors
moduleColors = labels2colors(net$colors)
table(moduleColors)
MEs = net$MEs;
geneTree = net$dendrograms[[1]];
save(MEs, moduleLabels, moduleColors, geneTree, file = "network-reconstruction.RData")
```



##########################################
Relate modules to external clinical traits
##########################################

```{r}
# Load the expression and trait data saved in the first part
lnames = load(file = "WGCNA-input.RData");
#The variable lnames contains the names of loaded variables.
lnames
# Load network data saved in the second part.
lnames = load(file = "network-reconstruction.RData");
lnames
```

```{r}
# Define numbers of genes and samples
nGenes = ncol(data.filtered.dcm);
nSamples = nrow(data.filtered.dcm);
# Recalculate MEs with color labels
MEs0 = moduleEigengenes(data.filtered.dcm, moduleColors)$eigengenes
MEs = orderMEs(MEs0)
moduleTraitCor = cor(MEs, datTraits, use = "p");
moduleTraitPvalue = corPvalueStudent(moduleTraitCor, nSamples);
```

```{r}
sizeGrWindow(20,20)
# Will display correlations and their p-values
textMatrix =  paste(signif(moduleTraitCor, 2), "\n(",
                           signif(moduleTraitPvalue, 1), ")", sep ="");
dim(textMatrix) = dim(moduleTraitCor)
par(mar = c(8, 8.5, 3, 3));

# Display the correlation values within a heatmap plot
labeledHeatmap(Matrix = moduleTraitCor,
               xLabels = names(datTraits),
               yLabels = names(MEs),
               ySymbols = names(MEs),
               colorLabels = FALSE,
               colors = blueWhiteRed(50),
               textMatrix = textMatrix,
               setStdMargins = FALSE,
               cex.text = 0.3,
               cex.lab.y = 0.5,
               zlim = c(-1,1),
               main = paste("Module-trait relationships"))
```

```{r}
# Define variable time containing the time column of datTrait
Diet = as.data.frame(datTraits$Diet);
names(Diet) = "diet"
# names (colors) of the modules
modNames = substring(names(MEs), 3)

geneModuleMembership = as.data.frame(cor(data.filtered.dcm, MEs, use = "p"));
MMPvalue = as.data.frame(corPvalueStudent(as.matrix(geneModuleMembership), nSamples));

names(geneModuleMembership) = paste("MM", modNames, sep="");
names(MMPvalue) = paste("p.MM", modNames, sep="");

geneTraitSignificance = as.data.frame(cor(data.filtered.dcm, Diet, use = "p"));
GSPvalue = as.data.frame(corPvalueStudent(as.matrix(geneTraitSignificance), nSamples));

names(geneTraitSignificance) = paste("GS.", names(Diet), sep="");
names(GSPvalue) = paste("p.GS.", names(Diet), sep="");
```

```{r}
#module = "red"
#module = "black"
module = "green"
#module = "turquoise"
column = match(module, modNames);
moduleGenes = moduleColors==module;

sizeGrWindow(7, 7);
par(mfrow = c(1,1));
verboseScatterplot(abs(geneModuleMembership[moduleGenes, column]),
                   abs(geneTraitSignificance[moduleGenes, 1]),
                   xlab = paste("Module Membership in", module, "module"),
                   ylab = "Gene significance for diet",
                   main = paste("Module membership vs. gene significance\n"),
                   cex.main = 1.2, cex.lab = 1.2, cex.axis = 1.2, col = module)
```

```{r}
# Create the starting data frame
geneInfo0 = data.frame(Gene.ID = colnames(data.filtered.dcm),
                      moduleColor = moduleColors,
                      geneTraitSignificance,
                      GSPvalue)

# Order modules by their significance 
modOrder = order(-abs(cor(MEs, Diet, use = "p")));

# Add module membership information in the chosen order
for (mod in 1:ncol(geneModuleMembership))
{
  oldNames = names(geneInfo0)
  geneInfo0 = data.frame(geneInfo0, geneModuleMembership[, modOrder[mod]], 
                         MMPvalue[, modOrder[mod]]);
  names(geneInfo0) = c(oldNames, paste("MM.", modNames[modOrder[mod]], sep=""),
                       paste("p.MM.", modNames[modOrder[mod]], sep=""))
}
# Order the genes in the geneInfo variable first by module color, then by geneTraitSignificance
geneOrder = order(geneInfo0$moduleColor, -abs(geneInfo0$GS.diet));
geneInfo = geneInfo0[geneOrder, ]
```

```{r}
write.csv(geneInfo, file = "geneInfo.csv", row.names = FALSE)
```


###################################
Network visualization 
###################################

```{r}
# Recalculate topological overlap if needed
TOM = TOMsimilarityFromExpr(data.filtered.dcm, power = 6);
#save(TOM, file = "WGCNA-TOM.RData")

# Select modules
#modules = c("black");
modules = c("green");
#modules = c("turquoise");
# Select module probes
probes = names(data.filtered.dcm)
inModule = is.finite(match(moduleColors, modules));
modProbes = probes[inModule];
# Select the corresponding Topological Overlap
modTOM = TOM[inModule, inModule];
dimnames(modTOM) = list(modProbes, modProbes)
# Export the network into edge and node list files Cytoscape can read
cyt = exportNetworkToCytoscape(modTOM,
  edgeFile = paste("QuadricepsCytoscapeInput-edges-", paste(modules, collapse="-"), ".txt", sep=""),
  nodeFile = paste("QuadricepsCytoscapeInput-nodes-", paste(modules, collapse="-"), ".txt", sep=""),
  weighted = TRUE,
  threshold = 0.05,
  nodeNames = modProbes,
  nodeAttr = moduleColors[inModule])

green = as.data.frame(cyt$nodeData$nodeName)
row.names(green) = cyt$nodeData$nodeName
write.csv(green,"Lgreen")
```

BlueModule = mEs$

```{r}
 
module_df <- data.frame(
  gene_id = names(net$colors),
  colors = labels2colors(net$colors))
  
modules_of_interest1 = c("green")
submodgreen = module_df %>%
  subset(colors %in% modules_of_interest1)

row.names(module_df) = module_df$gene_id

Genes_green <- row.names(submodgreen) 



require(gprofiler2)
gostresGreen = gost(query = Genes_green,
               organism = "mmusculus",
               numeric_ns = "ENTREZGENE_ACC")

 gostplot(gostresGreen, interactive = T)


```